# We have a conf directory, append it to BBPATH.
BBPATH .= ":${LAYERDIR}"

# Add recipes and recipe append files to BBFILES.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "bsp-ti"
BBFILE_PATTERN_bsp-ti := "^${LAYERDIR}/"
BBFILE_PRIORITY_bsp-ti = "15"

LAYERDEPENDS_bsp-ti = "core meta-ti-bsp"
LAYERSERIES_COMPAT_bsp-ti = "wrynose"

LICENSE_PATH += "${LAYERDIR}/licenses"
